version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: chat-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  api:
    build: .
    container_name: chat-api
    ports:
      - "4000:4000"
    env_file:
      - .env
    environment:
      MONGO_URI: mongodb://mongo:27017/chat_db
      # optional: override these if needed
      # ENABLE_CORS: "true"
      # CORS_ORIGIN: http://localhost:3000
    depends_on:
      - mongo

volumes:
  mongo_data:
